#!/usr/bin/env python3
"""Download the webfonts into static/fonts/ and regenerate static/fonts.css.

Run via `make fonts` from the repo root. Only needed when a family or weight
changes — the woff2 files and fonts.css are committed, so nothing fetches from
fonts.googleapis.com at runtime.

Note the DM Sans request: it has two axes (opsz, wght), so every value in the
tuple list has to name both. The templates used to build
`opsz,wght@9..40,300;400;500;600`, which Google answers with a 400 — so neither
family ever loaded and every page fell back to the generic sans-serif.
"""

import re
import subprocess
import sys
from pathlib import Path

GOOGLE_CSS = (
    "https://fonts.googleapis.com/css2"
    "?family=Barlow+Condensed:wght@600;700"
    "&family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500;9..40,600"
    "&display=swap"
)

# Google serves woff2 only to browsers; the default curl UA gets ttf.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

HEADER = """/* Self-hosted webfonts — generated by static/build_fonts.py (`make fonts`).
 *
 * Previously loaded from fonts.googleapis.com, which meant every page depended
 * on a third party for its typography and rendered wrong offline.
 */

"""

STATIC = Path(__file__).parent


def fetch(url: str, dest: Path | None = None) -> bytes | None:
    cmd = ["curl", "-sSfL", "-A", UA, url]
    if dest:
        cmd += ["-o", str(dest)]
        subprocess.run(cmd, check=True)
        return None
    return subprocess.run(cmd, check=True, capture_output=True).stdout


def main() -> int:
    css = fetch(GOOGLE_CSS).decode("utf-8")
    fonts_dir = STATIC / "fonts"
    fonts_dir.mkdir(exist_ok=True)

    downloaded: dict[str, str] = {}
    counters: dict[str, int] = {}
    rules: list[str] = []

    for block in re.findall(r"@font-face \{.*?\}", css, re.S):
        family = re.search(r"font-family: '([^']+)'", block).group(1)
        weight = re.search(r"font-weight: ([^;]+);", block).group(1).strip()
        style = re.search(r"font-style: ([^;]+);", block).group(1).strip()
        # Kept verbatim so the browser still picks the right subset per glyph.
        unicode_range = re.search(r"unicode-range: ([^;]+);", block).group(1).strip()
        url = re.search(r"url\((\S+?)\)", block).group(1)

        if url not in downloaded:
            key = f"{family.lower().replace(' ', '-')}-{weight.replace(' ', '')}"
            counters[key] = counters.get(key, 0) + 1
            name = f"{key}-{counters[key]}.woff2"
            fetch(url, fonts_dir / name)
            downloaded[url] = name

        rules.append(
            "@font-face {\n"
            f"  font-family: '{family}';\n"
            f"  font-style: {style};\n"
            f"  font-weight: {weight};\n"
            "  font-display: swap;\n"
            f"  src: url('/static/fonts/{downloaded[url]}') format('woff2');\n"
            f"  unicode-range: {unicode_range};\n"
            "}"
        )

    (STATIC / "fonts.css").write_text(HEADER + "\n\n".join(rules) + "\n", encoding="utf-8")
    print(f"{len(downloaded)} woff2 files, {len(rules)} @font-face rules")
    return 0


if __name__ == "__main__":
    sys.exit(main())
