#!/usr/bin/env python3
"""Derive the accent tint shades used in tailwind.config.js, and audit contrast.

Tailwind's own tints (blue-50, green-100, …) are mixed toward a cool white, so on
the warm #FDFBF8 card they read as a slightly blue-gray wash — the "non-gray
utilities keep the default cool palette" half of FE-L2. Instead of hand-picking
replacements, each tint here is the family's own 600 mixed into the paper colour,
so it carries the accent hue on the theme's own base.

The mid and dark shades (400-900) are deliberately left at Tailwind's values:
they carry text, their contrast is already tuned, and at that darkness the hue
base is not perceptible as "cool". Restraint, not uniformity.

Run: python web/tailwind/build_palette.py           (prints the palette + audit)
It generates values for a human to paste; the config holds literals so no build
step depends on this script.
"""

PAPER = "#FDFBF8"

# Tailwind 3.4 defaults for the families the templates actually use.
ANCHOR = {
    "amber":  "#d97706",
    "blue":   "#2563eb",
    "green":  "#16a34a",
    "orange": "#ea580c",
    "purple": "#9333ea",
    "red":    "#dc2626",
    "yellow": "#ca8a04",
}

# How much of the anchor hue each tint carries.
TINT_MIX = {50: 0.06, 100: 0.14, 200: 0.24}

# Shades left at Tailwind's values, per family (text and icon colours).
KEEP = {
    "amber":  {500: "#f59e0b", 600: "#d97706", 700: "#b45309", 800: "#92400e"},
    "blue":   {400: "#60a5fa", 500: "#3b82f6", 600: "#2563eb", 700: "#1d4ed8",
               800: "#1e40af", 900: "#1e3a8a"},
    "green":  {500: "#22c55e", 600: "#16a34a", 700: "#15803d", 800: "#166534"},
    "orange": {800: "#9a3412"},
    "purple": {800: "#6b21a8"},
    "red":    {400: "#f87171", 500: "#ef4444", 600: "#dc2626", 700: "#b91c1c",
               800: "#991b1b"},
    "yellow": {600: "#ca8a04", 800: "#854d0e"},
}

# Which tint shades each family needs, from the template inventory.
NEEDED_TINTS = {
    "amber": [50, 100, 200], "blue": [50, 100, 200], "green": [50, 100, 200],
    "orange": [100], "purple": [100], "red": [50, 100, 200], "yellow": [100],
}


def _rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def _hex(rgb):
    return "#" + "".join(f"{round(c):02X}" for c in rgb)


def mix(fg, bg, amount):
    """amount=0 -> bg, amount=1 -> fg."""
    a, b = _rgb(fg), _rgb(bg)
    return _hex(tuple(a[i] * amount + b[i] * (1 - amount) for i in range(3)))


def luminance(h):
    ch = [c / 255 for c in _rgb(h)]
    lin = [c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4 for c in ch]
    return 0.2126 * lin[0] + 0.7152 * lin[1] + 0.0722 * lin[2]


def contrast(fg, bg):
    a, b = luminance(fg), luminance(bg)
    hi, lo = max(a, b), min(a, b)
    return (hi + 0.05) / (lo + 0.05)


def build():
    palette = {}
    for family, shades in NEEDED_TINTS.items():
        entry = {s: mix(ANCHOR[family], PAPER, TINT_MIX[s]) for s in shades}
        entry.update(KEEP[family])
        palette[family] = dict(sorted(entry.items()))
    return palette


if __name__ == "__main__":
    palette = build()
    print("// generated by web/tailwind/build_palette.py")
    for family, shades in palette.items():
        print(f"{family}: {{")
        for shade, value in shades.items():
            note = "  // warm tint" if shade in TINT_MIX and shade in NEEDED_TINTS[family] else ""
            print(f"  {shade}: '{value}',{note}")
        print("},")

    print("\n--- tint shift vs Tailwind ---")
    tw = {"amber": {50: "#fffbeb", 100: "#fef3c7", 200: "#fde68a"},
          "blue": {50: "#eff6ff", 100: "#dbeafe", 200: "#bfdbfe"},
          "green": {50: "#f0fdf4", 100: "#dcfce7", 200: "#bbf7d0"},
          "orange": {100: "#ffedd5"}, "purple": {100: "#f3e8ff"},
          "red": {50: "#fef2f2", 100: "#fee2e2", 200: "#fecaca"},
          "yellow": {100: "#fef9c3"}}
    for family, shades in tw.items():
        for shade, old in shades.items():
            print(f"  {family}-{shade:<3} {old} -> {palette[family][shade]}")
